.github/workflows/ci.yml
docs/en/setup_env.md
docs/zh/setup_env.md

Docs: add cmake install

---

trpc/client/make_client_context.cc
trpc/client/make_client_context.h
trpc/client/service_proxy.cc
trpc/stream/grpc/grpc_server_stream_handler.cc
trpc/stream/http/async/server/stream_handler.cc
trpc/stream/trpc/trpc_server_stream.cc
trpc/stream/trpc/trpc_server_stream_handler.cc

- fix stream crash at ServerContext because it has been moved
- fix stream transinfo not pass into ServerContext

BugFix: Fix some problems at stream invoking

---

trpc/runtime/iomodel/reactor/default/tcp_connection.cc
trpc/transport/client/fiber/BUILD
trpc/transport/client/fiber/fiber_connector_group_manager.cc
trpc/transport/client/fiber/fiber_connector_group_manager.h
trpc/transport/client/fiber/fiber_transport.cc
trpc/transport/client/fiber/fiber_transport_test.cc

- Lowdown log level when TcpConnection ReadIoData error

Fix: Adjust FiberTransport to lowdown latency in busrt tcp connect scenario

---

trpc/runtime/iomodel/reactor/default/tcp_acceptor.cc
trpc/runtime/iomodel/reactor/default/tcp_acceptor_test.cc
trpc/runtime/iomodel/reactor/default/uds_acceptor.cc
trpc/runtime/iomodel/reactor/default/uds_acceptor_test.cc
trpc/runtime/iomodel/reactor/fiber/fiber_acceptor.cc
trpc/runtime/iomodel/reactor/fiber/fiber_tcp_connection_test.cc

BugFix: double close when accept fail

---

trpc/client/service_proxy_manager.cc
trpc/client/service_proxy_option_setter.cc
trpc/common/config/client_conf_parser.h
trpc/common/config/server_conf_parser.h
trpc/server/trpc_server.cc
trpc/tools/gdb_plugin/README.md
trpc/tools/gdb_plugin/gdb_fiber_plugin.py
trpc/transport/client/future/future_tcp_connector_group_manager.cc
trpc/transport/client/future/future_transport.cc

- unable to view fiber stack using gdb in python3
- prossible timeout in low qps situation when using connection reuse mode
- compatibility with the threadmodel_type field

BugFix: fix the following bugs

---

trpc/config/BUILD
trpc/config/trpc_conf_compatible.cc
trpc/config/trpc_conf_compatible_test.cc

issue: trpc::config::GetInt64() with json may coredump when real value is greater than INT32_MAX.
cause: asInt() of json-cpp with overflowed interge will assert failure.
fix: change asInt() to asInt64().

BugFix: fix coredump of trpc::config::GetInt64() with overflowed int32

---

trpc/client/service_proxy.cc
trpc/common/trpc_app.cc
trpc/common/trpc_app.h
trpc/runtime/iomodel/reactor/fiber/fiber_tcp_connection.cc
trpc/runtime/threadmodel/fiber/detail/fiber_entity.h
trpc/runtime/threadmodel/fiber/detail/scheduling/scheduling.h
trpc/runtime/threadmodel/fiber/detail/scheduling/v1/scheduling_impl.cc
trpc/runtime/threadmodel/fiber/detail/scheduling/v1/scheduling_impl.h
trpc/runtime/threadmodel/fiber/detail/scheduling/v2/local_queue.cc
trpc/runtime/threadmodel/fiber/detail/scheduling/v2/local_queue.h
trpc/runtime/threadmodel/fiber/detail/scheduling/v2/scheduling_impl.cc
trpc/runtime/threadmodel/fiber/detail/scheduling/v2/scheduling_impl.h
trpc/runtime/threadmodel/fiber/detail/scheduling_group.cc
trpc/runtime/threadmodel/fiber/detail/scheduling_group.h
trpc/runtime/threadmodel/fiber/detail/scheduling_group_test.cc
trpc/runtime/threadmodel/fiber/detail/waitable.cc
trpc/runtime/threadmodel/fiber/detail/waitable.h
trpc/stream/fiber_stream_job_scheduler.cc
trpc/transport/client/fiber/common/fiber_client_connection_handler.cc
trpc/transport/client/fiber/conn_complex/fiber_tcp_conn_complex_connector.cc
trpc/transport/client/fiber/conn_complex/fiber_udp_io_complex_connector.cc
trpc/transport/server/common/server_connection_handler.h
trpc/transport/server/fiber/fiber_bind_adapter.cc
trpc/util/log/default/sinks/local_file/hourly_file_sink.h

- optimize fiber mutex and condition_variable primitives to reduce fiber context switching
- supports updating configuration content after loading framework configuration

Feat: optimize fiber primitives to reduce fiber context switching

---

trpc/stream/trpc/trpc_client_stream_connection_handler.cc
trpc/stream/trpc/trpc_client_stream_connection_handler.h
trpc/stream/trpc/trpc_client_stream_handler.cc
trpc/stream/trpc/trpc_server_stream_handler.cc
trpc/transport/client/fiber/conn_complex/fiber_tcp_conn_complex_connector.cc

BugFix: fix trpc stream crash at client when connect failed with high frequency

---

trpc/server/rpc/unary_rpc_method_handler.h
trpc/server/server_context.cc
trpc/server/server_context.h
trpc/stream/stream.h

- Enable lite via `option optimize_for = LITE_RUNTIME;` at proto file

BugFix: fix pb derialization failed at server

---

trpc/runtime/threadmodel/separate/separate_scheduling.cc
trpc/runtime/threadmodel/separate/separate_scheduling.h
trpc/runtime/threadmodel/separate/separate_thread_model_test.cc

…essing SeparateScheduling as nullptr during startup

Feature: Modify the key of scheduling_map to std::string to avoid accessing SeparateScheduling as nullptr during startup

---

trpc/util/algorithm/BUILD
trpc/util/algorithm/hash_test.cc

Feature: add unit-testing building rules for trpc/util/algorithm

---

trpc/client/service_proxy.cc
trpc/client/service_proxy.h
trpc/client/service_proxy_manager.cc
trpc/client/service_proxy_manager.h
trpc/client/service_proxy_option.h
trpc/client/service_proxy_option_setter.cc
trpc/common/config/client_conf.h
trpc/common/config/client_conf_parser.h
trpc/common/config/default_value.h
trpc/common/trpc_app.cc
trpc/common/trpc_plugin.cc
trpc/coroutine/fiber_test.cc
trpc/server/non_rpc/non_rpc_service_impl.cc
trpc/transport/client/fiber/BUILD
trpc/transport/client/fiber/conn_complex/fiber_tcp_conn_complex_connector_group.cc
trpc/transport/client/fiber/conn_complex/fiber_tcp_conn_complex_connector_group.h
trpc/transport/client/fiber/fiber_connector_group_manager.cc
trpc/transport/client/fiber/fiber_connector_group_manager.h
trpc/transport/client/trans_info.h
trpc/util/concurrency/BUILD
trpc/util/concurrency/detail/BUILD
trpc/util/concurrency/detail/lightly_concurrent_hashmap_impl.h
trpc/util/concurrency/detail/lightly_concurrent_hashmap_impl_test.cc
trpc/util/concurrency/lightly_concurrent_hashmap.h
trpc/util/hazptr/hazptr_domain.cc
trpc/util/hazptr/hazptr_domain.h
trpc/util/hazptr/hazptr_object.cc
trpc/util/hazptr/hazptr_object.h

- add lightly concurrent hashmap
- GetProxy read wait-free
- fiber transport ConnectorGroupManager read wait-free

Optimize: optimize client class or datastruct, read wait-free

---

trpc/runtime/iomodel/reactor/default/tcp_acceptor.cc
trpc/runtime/iomodel/reactor/fiber/fiber_acceptor.cc
trpc/runtime/iomodel/reactor/fiber/fiber_reactor.cc

Feature: When accepting a server, if the created file descriptor (FD) is 0, 1, or 2, avoid asserting to prevent a core dump

Feature: When accepting a server, if the created file descriptor (FD) is 0, 1, or 2, avoid asserting to prevent a core dump

---

trpc/stream/http/async/stream.cc

- At content-length mode, invoking WriteDone of http async stream will write empty data to connection so that TcpClientConnection canculate wrong io_msgs_ size.

BugFix: connection can't send data while http async stream write empty data.

---

trpc/client/http/http_service_proxy.cc
trpc/client/http/http_service_proxy_test.cc
trpc/codec/http/http_protocol.cc
trpc/codec/http/http_protocol.h
trpc/codec/http/http_protocol_test.cc
trpc/util/http/field_map.h
trpc/util/http/field_map_test.cc

- Fix the issue where metrics reports as correct when the HTTP client's asynchronous call returns an erroneous HTTP response code
- Fix the issue of rpcz not correctly obtaining the size of the HTTP client response packet
- Fix the case sensitivity issue in key comparison for HttpHeader.SetIfNotPresent interfac

Bugfix: Fix some HTTP-related issues

---

trpc/config/trpc_conf_compatible.cc
trpc/config/trpc_conf_compatible_test.cc
trpc/runtime/iomodel/reactor/fiber/writing_buffer_list.cc
trpc/server/rpc/unary_rpc_method_handler.h

- fix TransformConfig return true convert not valid json-string to json-object
- complete pb-lite seriazation support
- fix connection block problem when WritingBufferList at high payload

fix some problems(json parser/pb lite/connection block)

---

trpc/util/log/default/default_log.h

set `format` from parent config when there is not format of the sink config

Bugfix: Set format from parent config

---

.bazelignore

When compiling with bazel, ignore all files under cmake_third_party so that `bazel build...` works properly

chore: add .bazelignore

---

trpc/coroutine/fiber.h
trpc/coroutine/fiber_test.cc

see also https://github.com/Tencent/flare/pull/66, https://github.com/Tencent/flare/pull/74

fix: fiber calling with arguments

---

cmake/gtest_gmock.cmake
cmake/rapidjson.cmake
third_party/com_github_tencent_rapidjson/0001-remove-non-compiling-assignment-operator.patch
trpc/config/trpc_conf_compatible.h

Makes trpc successfully built under gcc-14.2 on Arch Linux.
Fixes #166.

fix compilation problems on gcc-14.2

---

trpc/client/service_proxy.h
trpc/client/service_proxy_manager.cc

将ServiceProxy中的ProxyStatistics、SelectTarget 和 CheckTimeout 从 private 改为 protected

【腾讯犀牛鸟开源课题实战】对接mysql sdk（主框架变动部分）

---

trpc/client/http/http_service_proxy.h
trpc/client/http/http_service_proxy_test.cc
trpc/transport/common/ssl/ssl.cc
trpc/util/object_pool/object_pool.h

- fixed the issue that the GetNonContiguousBufferContent interface of the HttpResponse output parameter using the HttpUnaryInvoke method could not obtain data
- fixed the issue that the https client would cause coredump if the ca_cert_path parameter is not configured

Bugfix: fixed the following bugs
